version: "3.8"
services:
  api_1:
    build:
      context: ./api_1
    # directly access debug
    # http://127.0.0.1:5070/products
    # ports:
    #   - 5070:5070
    volumes:
      - ./api_1/product_list_app.py:/src/product_list_app.py
    expose:
      - 5070
  nginx:
    restart: always
    image: nginx:1-alpine
    # access from nginx
    # http://127.0.0.1:8089/api_1/products
    ports:
      - 8089:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/index.html:/var/www/html/index.html
    depends_on:
      - api_1
